### ISSUE TITLE
What is offset range

### ISSUE THREAD

**Issue by longquanzheng** [uber-go/kafka-client#60]
https://github.com/uber-go/kafka-client/blob/4685b0dbc084bec4a6c8fd1808da1df19dc6b0d3/kafka/interfaces.go#L51

Hi can you give a little more background what is offset range and why do we need it? Looks like it is only being used for the DLQ topic? and WithRangeConsumers is deprecated.

**Comment by georgeteo** [comment]
DLQ consumer is implemented as a simple consumer. If you want to merge a DLQ from offset a to b you should call `MergeDLQ(ConsumerTopic, map[int32]OffsetRange])error` with the offset range for each partition that you want to receive data for. The library will start a simple consumer and consume the specified offset range and stop once it reaches offset b.
